# Generated by Django 4.0.7 on 2022-10-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='stock_run_notes',
            field=models.TextField(blank=True),
        ),
    ]
