# Generated by Django 4.0.7 on 2022-10-05 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_stock_end_date_alter_stock_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_count', models.IntegerField()),
                ('base_failure', models.IntegerField(blank=True)),
                ('bo_date', models.DateField()),
                ('vol_bo', models.IntegerField(blank=True)),
                ('vol_20', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('bo_vol_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('price_percent_run', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('base_length', models.IntegerField(blank=True)),
                ('sales_0qtr', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='stock',
            name='bases',
            field=models.ManyToManyField(to='core.stockbase'),
        ),
    ]
