# Generated by Django 4.0.7 on 2022-10-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_stockbase_stock_bases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockbase',
            name='base_failure',
            field=models.CharField(max_length=1),
        ),
    ]
