# Generated by Django 4.0.7 on 2022-10-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_stockbase_base_failure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockbase',
            name='price_percent_run',
        ),
        migrations.AddField(
            model_name='stockbase',
            name='price_percent_range',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='stockbase',
            name='bo_vol_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='stockbase',
            name='vol_20',
            field=models.IntegerField(blank=True),
        ),
    ]
