# Generated by Django 4.0.7 on 2022-10-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_stockbase_price_percent_run_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockbase',
            name='base_failure',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='stockbase',
            name='base_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockbase',
            name='bo_vol_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='stockbase',
            name='vol_20',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockbase',
            name='vol_bo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
