# Generated by Django 4.0.7 on 2022-10-07 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_stockbase_sales_0qtr'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockbase',
            name='stock_reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.stock'),
        ),
        migrations.AlterField(
            model_name='stockbase',
            name='ticker',
            field=models.CharField(max_length=10),
        ),
    ]
