# Generated by Django 4.0.8 on 2022-10-10 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_stockbase_stock_reference_alter_stockbase_ticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockbase',
            name='vol_20',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockbase',
            name='vol_bo',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
